### ISSUE TITLE
Pass command line arguments to sonar-scaner

### ISSUE THREAD

**Issue by bcaudan** [bcaudan/node-sonar-scanner#7]

**Comment by Zikoel** [comment]
Why this issue is closed without details? What is the manner to pass the command line arguments?

**Comment by bcaudan** [comment]
Hi @Zikoel,

You can pass command line arguments like other npm scripts:

```sh
npm run sonar-scanner -- --help
./node_modules/sonar-scanner/bin/sonar-scanner --help
```

**Comment by Zikoel** [comment]
Thank you! Another way is put the config file `sonar-project.properties` on the project root and insert here all the argument for SonarCube as explained [here](https://docs.sonarqube.org/display/SCAN/Analyzing+with+SonarQube+Scanner)
